### ISSUE TITLE
Compiler crash on SIL pass MandatoryInlining [5.7 Regression]

### ISSUE THREAD

**Issue by yonihemi** [apple/swift#60407]
**Describe the bug**
Debug build of a Swift Package depending on [Markup](https://github.com/SwiftDocOrg/Markup) (links with libxml2) crashes swift-frontend (regression from 5.6 to 5.7).

**Steps To Reproduce**
1. Unzip the attached project [UseMarkup.zip](https://github.com/apple/swift/files/9266662/UseMarkup.zip)
2. Run `swift build` with a 5.7 beta toolchain

**Expected behavior**
Project builds successfully.

**Actual behavior**
Compiler crashes during MandatoryInlining with [attached log](https://github.com/apple/swift/files/9266669/5.7.failure.log).

**Environment**
 - OS: macOS 12.4
 - Xcode Version: 14.0 beta 4 (14A5284g)

**Additional context**
- Already opened as `FB10178623` in beta 1, perhaps under incorrect category. Reproducible in betas 1 through 4.
- Crash doesn't happen in Release build - build is successful.
- Crash doesn't happen if building Markup package by itself.
- Crash doesn't happen in Swift 5.6 / Xcode 11.3 ([attached log](https://github.com/apple/swift/files/9266671/5.6.success.log)).

**Comment by orchetect** [comment]
I ran into this as well in a different Swift package. I found that it was caused by indirect use of methods that were exported from another module. After explicitly declaring the indirect module a dependency to my package target and importing it with an `import` statement, the issue was resolved. However it used to compile in Xcode 13 without issue.

**Comment by yonihemi** [comment]
Thanks @orchetect! Though this doesn't fix my use case. Plus the ideal is for the compiler to not crash even if the input is malformed (which I don't think is the case) but spit out an error.
